version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - TZ=America/Sao_Paulo
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
         - platform
  mysql-container:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=America/Sao_Paulo
    # volumes:
    #    - db_data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - platform
    volumes:
      - db_data:/var/lib/mysql/data
  app-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/score?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - TZ=America/Sao_Paulo
      - JPDA_ADDRESS=8080
      - JPDA_TRANSPORT=dt_socket
    depends_on:
      - mysql-container
      - rabbitmq
    networks:
         - platform
volumes:
    db_data: {}
networks:
  platform:
  