app-container:
  build:
    context: ../../../../
    dockerfile: ./src/main/resources/docker/Dockerfile
  ports:
    - 8080:8080
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/message?useSSL=false&allowPublicKeyRetrieval=true
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_RABBITMQ_HOST=rabbitmq-container
  depends_on:
    - rabbitmq-container
    - mysql-container
